server:
  port: 8889
  context-path: /experimentManagement
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.11.6.2:3306/test?useUnicode=true&characterEncoding=utf-8
  #    url: jdbc:mysql://192.168.1.50:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ev@z9w6
     # password: 123456
    max-wait: 10000
    max-active: 20
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=3000)
mybatis:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.bitnei.cloud.*.mapper
  configuration:
      map-underscore-to-camel-case: true
  mapperRefresher:
    period: 3
    initialDelay: 30
    enabled: true
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
smc:
  querySql: SELECT 1
download-path: /Users/jack/Documents/temp
