package com.bitnei.cloud.report.domain;

import lombok.Data;

import java.sql.Timestamp;

@Data
public class RawData {

    /** 点样编号 **/
    private String id;
    /** 点样人 **/
    private String sPeople;
    /** 点样时间 **/
    private Timestamp sTime;
    /** 孔位1 **/
    private Double vNo01;
    /** 孔位1 **/
    private Double vNo02;
    /** 孔位1 **/
    private Double vNo03;
    /** 孔位1 **/
    private Double vNo04;
    /** 孔位1 **/
    private Double vNo05;
    /** 孔位1 **/
    private Double vNo06;
    /** 孔位1 **/
    private Double vNo07;
    /** 孔位1 **/
    private Double vNo08;
    /** 孔位1 **/
    private Double vNo09;
    /** 孔位1 **/
    private Double vNo10;
    /** 孔位1 **/
    private Double vNo11;
    /** 孔位1 **/
    private Double vNo12;
    /** 孔位1 **/
    private Double vNo13;
    /** 孔位1 **/
    private Double vNo14;
    /** 孔位1 **/
    private Double vNo15;
    /** 孔位1 **/
    private Double vNo16;
    /** 孔位1 **/
    private Double vNo17;
    /** 孔位1 **/
    private Double vNo18;
    /** 孔位1 **/
    private Double vNo19;
    /** 孔位1 **/
    private Double vNo20;
    /** 孔位1 **/
    private Double vNo21;
    /** 孔位1 **/
    private Double vNo22;
    /** 孔位1 **/
    private Double vNo23;
    /** 孔位1 **/
    private Double vNo24;
    /** 孔位1 **/
    private Double vNo25;
    /** 孔位1 **/
    private Double vNo26;
    /** 孔位1 **/
    private Double vNo27;
    /** 孔位1 **/
    private Double vNo28;
    /** 孔位1 **/
    private Double vNo29;
    /** 孔位1 **/
    private Double vNo30;
    /** 孔位1 **/
    private Double vNo31;
    /** 孔位1 **/
    private Double vNo32;
    /** 孔位1 **/
    private Double vNo33;
    /** 孔位1 **/
    private Double vNo34;
    /** 孔位1 **/
    private Double vNo35;
    /** 孔位1 **/
    private Double vNo36;
    /** 孔位1 **/
    private Double vNo37;
    /** 孔位1 **/
    private Double vNo38;
    /** 孔位1 **/
    private Double vNo39;
    /** 孔位1 **/
    private Double vNo40;
    /** 孔位1 **/
    private Double vNo41;
    /** 孔位1 **/
    private Double vNo42;
    /** 孔位1 **/
    private Double vNo43;
    /** 孔位1 **/
    private Double vNo44;
    /** 孔位1 **/
    private Double vNo45;
    /** 孔位1 **/
    private Double vNo46;
    /** 孔位1 **/
    private Double vNo47;
    /** 孔位1 **/
    private Double vNo48;
    /** 孔位1 **/
    private Double vNo49;
    /** 孔位1 **/
    private Double vNo50;
    /** 孔位1 **/
    private Double vNo51;
    /** 孔位1 **/
    private Double vNo52;
    /** 孔位1 **/
    private Double vNo53;
    /** 孔位1 **/
    private Double vNo54;
    /** 孔位1 **/
    private Double vNo55;
    /** 孔位1 **/
    private Double vNo56;
    /** 孔位1 **/
    private Double vNo57;
    /** 孔位1 **/
    private Double vNo58;
    /** 孔位1 **/
    private Double vNo59;
    /** 孔位1 **/
    private Double vNo60;
    /** 孔位1 **/
    private Double vNo61;
    /** 孔位1 **/
    private Double vNo62;
    /** 孔位1 **/
    private Double vNo63;
    /** 孔位1 **/
    private Double vNo64;
    /** 孔位1 **/
    private Double vNo65;
    /** 孔位1 **/
    private Double vNo66;
    /** 孔位1 **/
    private Double vNo67;
    /** 孔位1 **/
    private Double vNo68;
    /** 孔位1 **/
    private Double vNo69;
    /** 孔位1 **/
    private Double vNo70;
    /** 孔位1 **/
    private Double vNo71;
    /** 孔位1 **/
    private Double vNo72;
    /** 孔位1 **/
    private Double vNo73;
    /** 孔位1 **/
    private Double vNo74;
    /** 孔位1 **/
    private Double vNo75;
    /** 孔位1 **/
    private Double vNo76;
    /** 孔位1 **/
    private Double vNo77;
    /** 孔位1 **/
    private Double vNo78;
    /** 孔位1 **/
    private Double vNo79;
    /** 孔位1 **/
    private Double vNo80;
    /** 孔位1 **/
    private Double vNo81;
    /** 孔位1 **/
    private Double vNo82;
    /** 孔位1 **/
    private Double vNo83;
    /** 孔位1 **/
    private Double vNo84;
    /** 孔位1 **/
    private Double vNo85;
    /** 孔位1 **/
    private Double vNo86;
    /** 孔位1 **/
    private Double vNo87;
    /** 孔位1 **/
    private Double vNo88;
    /** 孔位1 **/
    private Double vNo89;
    /** 孔位1 **/
    private Double vNo90;
    /** 孔位1 **/
    private Double vNo91;
    /** 孔位1 **/
    private Double vNo92;
    /** 孔位1 **/
    private Double vNo93;
    /** 孔位1 **/
    private Double vNo94;
    /** 孔位1 **/
    private Double vNo95;
    /** 孔位1 **/
    private Double vNo96;

}
