package com.bitnei.cloud.report.domain;

import lombok.Data;

@Data
public class RawData {

    /** 点样编号 **/
    private String id;
    private   String code;
    /** 点样人 **/
    private String speople;
    /** 点样时间 **/
    private String stime;

    private String createTime;
    /** 孔位1 **/
    private Double vno01;
    /** 孔位1 **/
    private Double vno02;
    /** 孔位1 **/
    private Double vno03;
    /** 孔位1 **/
    private Double vno04;
    /** 孔位1 **/
    private Double vno05;
    /** 孔位1 **/
    private Double vno06;
    /** 孔位1 **/
    private Double vno07;
    /** 孔位1 **/
    private Double vno08;
    /** 孔位1 **/
    private Double vno09;
    /** 孔位1 **/
    private Double vno10;
    /** 孔位1 **/
    private Double vno11;
    /** 孔位1 **/
    private Double vno12;
    /** 孔位1 **/
    private Double vno13;
    /** 孔位1 **/
    private Double vno14;
    /** 孔位1 **/
    private Double vno15;
    /** 孔位1 **/
    private Double vno16;
    /** 孔位1 **/
    private Double vno17;
    /** 孔位1 **/
    private Double vno18;
    /** 孔位1 **/
    private Double vno19;
    /** 孔位1 **/
    private Double vno20;
    /** 孔位1 **/
    private Double vno21;
    /** 孔位1 **/
    private Double vno22;
    /** 孔位1 **/
    private Double vno23;
    /** 孔位1 **/
    private Double vno24;
    /** 孔位1 **/
    private Double vno25;
    /** 孔位1 **/
    private Double vno26;
    /** 孔位1 **/
    private Double vno27;
    /** 孔位1 **/
    private Double vno28;
    /** 孔位1 **/
    private Double vno29;
    /** 孔位1 **/
    private Double vno30;
    /** 孔位1 **/
    private Double vno31;
    /** 孔位1 **/
    private Double vno32;
    /** 孔位1 **/
    private Double vno33;
    /** 孔位1 **/
    private Double vno34;
    /** 孔位1 **/
    private Double vno35;
    /** 孔位1 **/
    private Double vno36;
    /** 孔位1 **/
    private Double vno37;
    /** 孔位1 **/
    private Double vno38;
    /** 孔位1 **/
    private Double vno39;
    /** 孔位1 **/
    private Double vno40;
    /** 孔位1 **/
    private Double vno41;
    /** 孔位1 **/
    private Double vno42;
    /** 孔位1 **/
    private Double vno43;
    /** 孔位1 **/
    private Double vno44;
    /** 孔位1 **/
    private Double vno45;
    /** 孔位1 **/
    private Double vno46;
    /** 孔位1 **/
    private Double vno47;
    /** 孔位1 **/
    private Double vno48;
    /** 孔位1 **/
    private Double vno49;
    /** 孔位1 **/
    private Double vno50;
    /** 孔位1 **/
    private Double vno51;
    /** 孔位1 **/
    private Double vno52;
    /** 孔位1 **/
    private Double vno53;
    /** 孔位1 **/
    private Double vno54;
    /** 孔位1 **/
    private Double vno55;
    /** 孔位1 **/
    private Double vno56;
    /** 孔位1 **/
    private Double vno57;
    /** 孔位1 **/
    private Double vno58;
    /** 孔位1 **/
    private Double vno59;
    /** 孔位1 **/
    private Double vno60;
    /** 孔位1 **/
    private Double vno61;
    /** 孔位1 **/
    private Double vno62;
    /** 孔位1 **/
    private Double vno63;
    /** 孔位1 **/
    private Double vno64;
    /** 孔位1 **/
    private Double vno65;
    /** 孔位1 **/
    private Double vno66;
    /** 孔位1 **/
    private Double vno67;
    /** 孔位1 **/
    private Double vno68;
    /** 孔位1 **/
    private Double vno69;
    /** 孔位1 **/
    private Double vno70;
    /** 孔位1 **/
    private Double vno71;
    /** 孔位1 **/
    private Double vno72;
    /** 孔位1 **/
    private Double vno73;
    /** 孔位1 **/
    private Double vno74;
    /** 孔位1 **/
    private Double vno75;
    /** 孔位1 **/
    private Double vno76;
    /** 孔位1 **/
    private Double vno77;
    /** 孔位1 **/
    private Double vno78;
    /** 孔位1 **/
    private Double vno79;
    /** 孔位1 **/
    private Double vno80;
    /** 孔位1 **/
    private Double vno81;
    /** 孔位1 **/
    private Double vno82;
    /** 孔位1 **/
    private Double vno83;
    /** 孔位1 **/
    private Double vno84;
    /** 孔位1 **/
    private Double vno85;
    /** 孔位1 **/
    private Double vno86;
    /** 孔位1 **/
    private Double vno87;
    /** 孔位1 **/
    private Double vno88;
    /** 孔位1 **/
    private Double vno89;
    /** 孔位1 **/
    private Double vno90;
    /** 孔位1 **/
    private Double vno91;
    /** 孔位1 **/
    private Double vno92;
    /** 孔位1 **/
    private Double vno93;
    /** 孔位1 **/
    private Double vno94;
    /** 孔位1 **/
    private Double vno95;
    /** 孔位1 **/
    private Double vno96;

    private String secondaryCoefficient;
    private String oneCoefficient;
    private String parameter;

    private String secondaryCoefficientAgain;
    private String oneCoefficientAgain;
    private String parameterAgain;
}
